<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
    <RootNamespace />
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <!--nuget build properties-->
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!--nuget package properties-->
  <PropertyGroup>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <!--TODO only use current ticks if you are doing a "local"--> <!--you should do a "package version suffix" in the directory.build that way you don't repeat the logic everywhere-->
    <!--TODO what does "release" look like? you should have a script for doing this; at the very least, the script should take you through each manual step one at a time-->
    <PackageVersion>1.0.0.0-$(CurrentTicks)</PackageVersion>
    <PackageProjectUrl>https://github.com/ravudet/Fx.Core/tree/main/source/Fx.Core</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>TODO link to the github release notes</PackageReleaseNotes>
    <DevelopmentDependency>false</DevelopmentDependency>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
    
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
