<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
    <RootNamespace />
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(LangVersion)' == '13.0'">
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <!--nuget build properties-->
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!--nuget package properties-->
  <PropertyGroup>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <!--TODO you are here, but up above, i think you can have nullable condition on the `nullable` element itself; and also i think you can have the condition use something like "net90orgreater"-->
    <VersionPrefix>1.0.0</VersionPrefix>
    <PackageProjectUrl>https://github.com/ravudet/Fx.Core/tree/main/source/Fx.Core</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>TODO link to the github release notes</PackageReleaseNotes>
    <DevelopmentDependency>false</DevelopmentDependency>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
    
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="foo" BeforeTargets="Build">
    <!--<Error Text="$(LangVersion) - $(Nullable)" />-->
  </Target>
  
</Project>
