<Project>
  <PropertyGroup>
    <CurrentTicks>$([System.DateTime]::Now.Ticks)</CurrentTicks>
    <PackageVersionSuffix Condition="'$(Fx.Release)' == 'true'">-$(CurrentTicks)</PackageVersionSuffix>
  </PropertyGroup>

  <!--nuget build properties-->
  <PropertyGroup>
    <PackageId>$(MSBuildProjectName)</PackageId>
    <NoPackageAnalysis>false</NoPackageAnalysis>
    <PackageOutputPath>$(MSBuildThisFileDirectory)\packages</PackageOutputPath>
  </PropertyGroup>

  <!--nuget package properties-->
  <PropertyGroup>
    <Authors>ravudet</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/ravudet/Fx.Core</RepositoryUrl>
  </PropertyGroup>

</Project>