<Project Sdk="MSTest.Sdk/3.6.4">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace />
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>

  <PropertyGroup>
    <MyCustomProperty>ravudet-testing</MyCustomProperty>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="actualconfig.config" />
  </ItemGroup>

  <ItemGroup>
    <!--<Content Include="app.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>-->
    <!--<Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>-->
    <Content Include="actualconfig.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="testhost.dll.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.12" />
  </ItemGroup>
  
  <Target Name="UpdateOutputConfig" AfterTargets="Build">
    <XmlPoke XmlInputPath="C:\github\Fx.Core\source\PackageTests\bin\Debug\net9.0\actualconfig.config" Query="/configuration/appSettings/add[@key='BuildNumber']/@value" Value="$(MyCustomProperty)" />
  </Target>

</Project>
