<Project Sdk="MSTest.Sdk/3.6.4">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace />
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="Microsoft.CodeAnalysis" Version="3.11.0" />
    
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" Version="1.1.4" />
    
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.300" GeneratePathProperty="true">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis.NetAnalyzers">
      <HintPath>$(PkgMicrosoft_CodeAnalysis_NetAnalyzers)\analyzers\dotnet\Microsoft.CodeAnalysis.NetAnalyzers.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="..\Fx.Analyzers.GlobalConfig\content\Fx.Analyzers.GlobalConfig.globalconfig" Link="Fx.Analyzers.GlobalConfig.globalconfig" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Content\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fx.Analyzers\Fx.Analyzers.csproj" />
  </ItemGroup>
  
  <Target Name="RemoveResources" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <Compile Remove="Content\**" />
      <EmbeddedResource Include="Content\**" />
    </ItemGroup>
  </Target>

</Project>
