<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <!--<ItemGroup>
        <Reference Include="Microsoft.CodeAnalysis.Analyzers">
            <HintPath>C:\github\OddTrotter\Fx.Core\Fx.Test.Tests\stuff\Microsoft.CodeAnalysis.Analyzers.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.CSharp.Analyzers">
            <HintPath>C:\github\OddTrotter\Fx.Core\Fx.Test.Tests\stuff\Microsoft.CodeAnalysis.CSharp.Analyzers.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.CSharp">
            <HintPath>C:\github\OddTrotter\Fx.Core\Fx.Test.Tests\stuff\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis">
            <HintPath>C:\github\OddTrotter\Fx.Core\Fx.Test.Tests\stuff\Microsoft.CodeAnalysis.dll</HintPath>
        </Reference>
    </ItemGroup>-->
    
    <ItemGroup>
        <Compile Update="Resources.Designer.cs" DesignTime="True" AutoGen="True" DependentUpon="Resources.resx" />
        <EmbeddedResource Update="Resources.resx" Generator="ResXFileCodeGenerator" LastGenOutput="Resources.Designer.cs" />
    </ItemGroup>

</Project>
