<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace />
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Fx.Core</PackageId>
    <PackageVersion>1.0.0.0</PackageVersion> <!--TODO-->
    <Authors>ravudet</Authors> <!--TODO-->
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance> <!--TODO-->
    <Description>Fx.Core</Description>
    <PackageReleaseNotes>TODO</PackageReleaseNotes>
    <Copyright>Copyright</Copyright> <!--TODO-->
    <!--<PackageTags>Analyzer1, analyzers</PackageTags>-->
    <!--<DevelopmentDependency>true</DevelopmentDependency>-->
    <!--<NoPackageAnalysis>true</NoPackageAnalysis>-->
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>..\Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp.Scripting">
      <HintPath>..\Microsoft.CodeAnalysis.CSharp.Scripting.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
