<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fx.Core\Fx.Core.csproj" />
  </ItemGroup>

</Project>
