<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace />
  </PropertyGroup>

  <!--nuget build properties-->
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!--nuget package properties-->
  <PropertyGroup>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <VersionPrefix>1.0.0</VersionPrefix>
    <PackageProjectUrl>TODO</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>https://github.com/ravudet/Fx.Core/releases/tag/$(PackageId)_$(VersionPrefix)</PackageReleaseNotes>
    <DevelopmentDependency>false</DevelopmentDependency>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <!--TODO test a global config-->
    <!--TODO test a global config that uses the custom analyzer-->
    <None Include="build\Fx.Analyzers.GlobalConfig.props" PackagePath="build" Pack="true" />
    <None Include="content\Fx.Analyzers.GlobalConfig.globalconfig" PackagePath="content" Pack="true" />
    <None Include="tools\nothing.ps1" PackagePath="tools" Pack="true" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fx.Analyzers\Fx.Analyzers.csproj" />
  </ItemGroup>

</Project>
